In [ ]:
#DATA POINTS AND DIRECTION
#what is a vector
#A vector is a list of numbers that has some parameters

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
#study_hours,attendance,previous_marks
students_a=np.array([6,85,78])
students_b=np.array([3,70,55])

print("Student A vector:",students_a)
print("students B vector:",students_b)


Student A vector: [ 6 85 78]
students B vector: [ 3 70 55]


In [23]:
students = pd.DataFrame({
    "name": ["Aarav", "Riya", "Kabir", "Meera", "Dev", "Sara"],
    "study_hours": [6, 3, 8, 2, 5, 7],
    "attendance": [85, 70, 90, 60, 78, 92],
    "previous_marks": [78, 55, 88, 35, 65, 84],
    "final_marks": [82, 58, 91, 40, 70, 88]
})


In [24]:
feature_columns=["study_hours","attendance","previous_marks"]
student_vectors=students[feature_columns].values
print(student_vectors)

[[ 6 85 78]
 [ 3 70 55]
 [ 8 90 88]
 [ 2 60 35]
 [ 5 78 65]
 [ 7 92 84]]


In [26]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(student_vectors)

similarity_df = pd.DataFrame(
    similarity_matrix,
    index=students["name"],
    columns=students["name"]
)

similarity_df

name,Aarav,Riya,Kabir,Meera,Dev,Sara
name,,,,,,
Aarav,1.000000,0.996913,0.999434,0.976875,0.998860,0.999988
Riya,0.996913,1.000000,0.993724,0.990505,0.999467,0.997017
Kabir,0.999434,0.993724,1.000000,0.969344,0.996756,0.999391
Meera,0.976875,0.990505,0.969344,1.000000,0.985958,0.977304
Dev,0.998860,0.999467,0.996756,0.985958,1.000000,0.998956
Sara,0.999988,0.997017,0.999391,0.977304,0.998956,1.000000


In [ ]:
#An embedding is a vector that represents meaning
#words,images,products,users,documents

In [ ]:
#cat-dog || dog-banana || cat-bottle ||monkey-banana

In [ ]:
#Models do not read english directly
#they use tokens

In [31]:
sentence="The movie was not good"
tokens=sentence.lower().split()
print(tokens)

['the', 'movie', 'was', 'not', 'good']


In [33]:
#assigning token ids
vocab={
    "the":1,
    "movie":2,
    "was":3,
    "not":4,
    "good":5
}
token_ids=[vocab[word] for word in tokens]
print(token_ids)


[1, 2, 3, 4, 5]


In [35]:
#text as a sequence data
positive_words = ["good", "great", "amazing", "excellent", "love"]
negative_words = ["bad", "terrible", "poor", "hate", "boring"]

def simple_sentiment(sentence):
    words = sentence.lower().replace(".", "").split()
    
    score = 0
    
    for word in words:
        if word in positive_words:
            score += 1
        elif word in negative_words:
            score -= 1
            
    if score > 0:
        return "Positive"
    elif score < 0:
        return "Negative"
    else:
        return "Neutral"
        
print(simple_sentiment("The movie was good"))
print(simple_sentiment("The movie was bad"))
print(simple_sentiment("The movie was not good"))

Positive
Negative
Positive


In [ ]:
#RNN
#recurrent-something repeats
#In RNN,the same cell is used again and again across sequence
